# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=30)),
                ('arena', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('number', models.IntegerField(default=170)),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=30)),
                ('height', models.IntegerField(default=170)),
                ('age', models.IntegerField(default=170)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Player')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.Manager'),
        ),
    ]
