# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_auto_20160312_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='previous_clubs',
            field=models.ManyToManyField(related_name='playerspreviousclubs', through='clubs.PreviousClubs', to='clubs.Club'),
        ),
    ]
